### ISSUE TITLE
Error: undefined symbol: pg_get_querydef

### ISSUE THREAD

**Issue by koureasstavros** [sraoss/pg_ivm#38]
I tried pg_ivm extension in Postgres15 and works as excepted.
I tried also  pg_ivm extension in Postgres14, after installation, running the command:
`CREATE EXTENSION pg_ivm;`
throws an error
`ERROR:  could not load library "/usr/lib/postgresql/14/lib/pg_ivm.so": /usr/lib/postgresql/14/lib/pg_ivm.so: undefined symbol: pg_get_querydef`

I think this function exists on PostgreSQL14
Any ideas?

**Comment by yugo-n** [comment]
Maybe, you missed to rebuild (make clean & make) pg_ivm before installation (make install) to PostgreSQL 14.

**Comment by koureasstavros** [comment]
Thanks, that was my issue, I had build it first for PG15 and make clean & make did the trick.
