### ISSUE TITLE
do you plan to include back the CTE/subquery/aggregation work?

### ISSUE THREAD

**Issue by docteurklein** [sraoss/pg_ivm#4]
First, thank you for your work, it's really interesting!

I lurked in the [commits from the pg fork](https://github.com/sraoss/pgsql-ivm/commit/c92da4953318c60c3fd427e821f4590cc8b070ad) and wanted to apply the patches here, but I wonder how hard it would be?
Is the upstream patch to `inline_cte` necessary?

Thanks!

**Comment by yugo-n** [comment]
> First, thank you for your work, it's really interesting!
Thanks!

> I lurked in the [commits from the pg fork](https://github.com/sraoss/pgsql-ivm/commit/c92da4953318c60c3fd427e821f4590cc8b070ad) and wanted to apply the patches here, but I wonder how hard it would be?

We decided to start from the simple feature at the initial version, but we plan to support CTE and subqueries. After confirming that they works well, we are going to introduce left features of the [pgsql-ivm](https://github.com/sraoss/pgsql-ivm/) repository into the extension.

> Is the upstream patch to inline_cte necessary?

I plan to use the code of the original PostgreSQL by duplicate.

**Comment by yugo-n** [comment]
As of pg_ivm 1.2, aggregates and simple sub-queries in FROM clause are supported. 

CTE, EXISTS, and outer-join are left for feature releases.
