### ISSUE TITLE
ERROR:  extension "pg_ivm" has no installation script nor update path for version "1.4"

### ISSUE THREAD

**Issue by jaulz** [sraoss/pg_ivm#43]
When I try to install the latest version I'm stumbling across this error:
````
ERROR:  extension "pg_ivm" has no installation script nor update path for version "1.4"
`````

In my case it helped to create a dummy file:
```
touch /usr/share/postgresql/14/extension/pg_ivm--1.3--1.4.sql
```

**Comment by yugo-n** [comment]
Thank you for pointing out this!
pg_ivm--1.3--1.4.sql already exists but stupidly forgot updating Makefile, so it would not be installed. I'll fix it.

**Comment by mirzap** [comment]
Can you update release to contain this fix.. 1.4.1 or something. Thanks.

**Comment by yugo-n** [comment]
Released.
https://github.com/sraoss/pg_ivm/releases/tag/v1.4.1
