### ISSUE TITLE
IVM Installation

### ISSUE THREAD

**Issue by satheeshcitrus** [sraoss/pg_ivm#74]
While installing in docker machine  error comes like below
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o createas.o createas.c
make: gcc: No such file or directory
make: *** [<builtin>: createas.o] Error 127
 Pls help me

**Comment by yugo-n** [comment]
> make: gcc: No such file or directory

The problem would be that gcc is not installed in your system.
