### ISSUE TITLE
IVM installation Docker 

### ISSUE THREAD

**Issue by satheeshcitrus** [sraoss/pg_ivm#75]
While installing in docker machine error comes like below
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o createas.o createas.c
createas.c:12:10: fatal error: postgres.h: No such file or directory
   12 | #include "postgres.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: createas.o] Error 1
Pls help me

**Comment by yugo-n** [comment]
You have to install PostgreSQL devel package  (for example, postgresql14-devel or postgresql-server-dev-14) or install PostgreSQL from the source code, and also you have to set PATH to the pg_config command of your PostgreSQL. Could you please confirm the above?

**Comment by satheeshcitrus** [comment]
ok, it is fine
