### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [sraoss/pg_ivm#90]
Hi,

Latest release (1.8) fails to build against PostgreSQL 17. v17beta2 is already out. Can you please take a look?

Thanks!

Devrim

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o subselect.bc subselect.c
matview.c:83:2: error: unknown type name 'OverrideSearchPath'
   83 |         OverrideSearchPath *search_path;        /* search_path used for parsing
      |         ^
matview.c:266:13: error: use of undeclared identifier 'RangeVarCallbackOwnsTable'
  266 |                                                                                   RangeVarCallbackOwnsTable, NULL);
      |                                                                                   ^
matview.c:3069:3: error: call to undeclared function 'OverrideSearchPathMatchesCurrent'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3069 |                 OverrideSearchPathMatchesCurrent(entry->search_path))
      |                 ^
matview.c:3113:23: error: call to undeclared function 'GetOverrideSearchPath'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3113 |         entry->search_path = GetOverrideSearchPath(TopMemoryContext);
      |                              ^
4 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: matview.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
matview.c:83:9: error: unknown type name ‘OverrideSearchPath’
   83 |         OverrideSearchPath *search_path;        /* search_path used for parsing
      |         ^~~~~~~~~~~~~~~~~~
matview.c: In function ‘ExecRefreshImmv’:
matview.c:266:83: error: ‘RangeVarCallbackOwnsTable’ undeclared (first use in this function); did you mean ‘RangeVarCallbackOwnsRelation’?
  266 |                                                                                   RangeVarCallbackOwnsTable, NULL);
      |                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                   RangeVarCallbackOwnsRelation
matview.c:266:83: note: each undeclared identifier is reported only once for each function it appears in
matview.c: In function ‘mv_FetchPreparedPlan’:
matview.c:3069:17: error: implicit declaration of function ‘OverrideSearchPathMatchesCurrent’ [-Wimplicit-function-declaration]
 3069 |                 OverrideSearchPathMatchesCurrent(entry->search_path))
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
matview.c: In function ‘mv_HashPreparedPlan’:
matview.c:3113:30: error: implicit declaration of function ‘GetOverrideSearchPath’ [-Wimplicit-function-declaration]
 3113 |         entry->search_path = GetOverrideSearchPath(TopMemoryContext);
      |                              ^~~~~~~~~~~~~~~~~~~~~
matview.c:3113:28: error: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 3113 |         entry->search_path = GetOverrideSearchPath(TopMemoryContext);
      |                            ^
make[1]: *** [<builtin>: matview.o] Error 1

**Comment by devrimgunduz** [comment]
ping

**Comment by yugo-n** [comment]
Sorry, I forgot to update here.
pg_ivm 1.9 that can be built with PG17 was released yesterday.

**Comment by yugo-n** [comment]
@devrimgunduz 
pg_ivm 1.9 that can be built with PG17 was released yesterday.

**Comment by yugo-n** [comment]
https://github.com/sraoss/pg_ivm/releases/tag/v1.9
