### ISSUE TITLE
Missing file `pg_ivm--1.8--1.9.sql`

### ISSUE THREAD

**Issue by epoweripione** [sraoss/pg_ivm#93]
Error `/usr/bin/install: cannot stat './/pg_ivm--1.8--1.9.sql': No such file or directory` when install 1.9

**Comment by salilsaifuddin** [comment]
I am experiencing the same error when trying to install version 1.9:
```
Error /usr/bin/install: cannot stat './/pg_ivm--1.8--1.9.sql': No such file or directory
```

**Comment by yugo-n** [comment]
I'm sorry. I accidentally forgot to push the update script pg_ivm--1.8--1.9.sql

I added this file. Please fetch the latest branch or make a empty file named pg_ivm--1.8--1.9.sql, and try to install it again.

**Comment by yugo-n** [comment]
Fixed.
https://github.com/sraoss/pg_ivm/commit/bb3c999c05cf75848f2e21ce1fba7496ec77d4c4
