### ISSUE TITLE
Drop Extension failure

### ISSUE THREAD

**Issue by ibhaskar2** [sraoss/pg_ivm#97]
Dropping extension fails with error
<img width="474" alt="Screenshot 2024-08-23 at 12 12 47 PM" src="https://github.com/user-attachments/assets/95ed1a12-39d6-4491-9cba-b1855a62caa9">

**Comment by ibhaskar2** [comment]
Raised a PR for fixing this issue https://github.com/sraoss/pg_ivm/pull/96

**Comment by yugo-n** [comment]
This was fixed by #96.
